server:
  port: 9093
  contextPath: /product-portal

databasens:
  service:
    url: http://localhost:9099/databasens/customers
    
databases:
  service:
    url: http://localhost:9091/databases/customers

customer:
  service:
    url: http://localhost:9092/customer-portal/

