server:
  port: 9092
  contextPath: /customer-portal

databasens:
  service:
    url: http://localhost:9099/databasens/customers
    
databases:
  service:
    url: http://localhost:9091/databases/customers

product:
  service:
    url: http://localhost:9093/product-portal/

spring:
  freemarker:
    cache: false
